image: Visual Studio 2017

version: '0.3.{build}'

configuration:
- Debug
- Release

platform: x86

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15

install:
    - call CI\appveyor\install.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%          # CMAKE_CONFIGURE_FLAGS and CMAKE_BUILD_FLAGS are defined in CI\appveyor\install.bat
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

artifacts:
    - path: TDEngine2_SDK.zip

after_build:
    #create zip archive with all the binaries and documentation
    - cmd: CI\appveyor\after_build.bat

deploy:
  release: TDEngine2_SDK-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: aKw3Gnd9exu0Fdz7DUdiOj36rMkyCc9h+5y2KlbLqBftXwm/Atq3wndgXnztWeKf
  artifact: /.*\.zip/            
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true