image: Visual Studio 2017

version: '0.3.{build}'

configuration:
- Debug
- Release

platform: x86

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15
    CI_DEPLOY_TOKEN:
        secure: aKw3Gnd9exu0Fdz7DUdiOj36rMkyCc9h+5y2KlbLqBftXwm/Atq3wndgXnztWeKf

install:
    - call CI\appveyor\install.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%          # CMAKE_CONFIGURE_FLAGS and CMAKE_BUILD_FLAGS are defined in CI\appveyor\install.bat
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

artifacts:
    - path: TDEngine2_SDK.zip

after_build:
    #create zip archive with all the binaries and documentation
    7z a TDEngine2_SDK.zip %APPVEYOR_BUILD_FOLDER%\TDEngine2\bin\%CONFIGURATION%\*.dll^
    %APPVEYOR_BUILD_FOLDER%\TDEngine2\bin\%CONFIGURATION%\*.lib^
    %APPVEYOR_BUILD_FOLDER%\TDEngine2\bin\%CONFIGURATION%\*.pdb^
    %APPVEYOR_BUILD_FOLDER%\TDEngine2\bin\%CONFIGURATION%\*.exp^
    %APPVEYOR_BUILD_FOLDER%\TDEngine2\bin\%CONFIGURATION%\*.exe^
    %APPVEYOR_BUILD_FOLDER%\Resources^
    %APPVEYOR_BUILD_FOLDER%\README.md^
    %APPVEYOR_BUILD_FOLDER%\LICENSE^
    %APPVEYOR_BUILD_FOLDER%\CHANGELOG.md

deploy:
  release: TDEngine2_SDK-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: %CI_DEPLOY_TOKEN%
  artifact: /.*\.zip/            
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true