image: Visual Studio 2017

version: '0.4.{build}'

configuration:
- Debug
- Release

platform: x86

environment:
    matrix:
        # - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15

install:
    - call CI\appveyor\install.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - cd build
    - set TDE2_SKIP_ERROR_WAIT_USER_RESPONSE=1 # Skip pause when error's happened
    - call prepare_build_generic_win.bat %CMAKE_CONFIGURE_FLAGS% %CONFIGURATION%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

artifacts:
    - path: TDEngine2_SDK.zip

after_build:
    - cmd: 7z a TDEngine2_SDK.zip %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\ %APPVEYOR_BUILD_FOLDER%\Resources %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\CHANGELOG.md %APPVEYOR_BUILD_FOLDER%\TDEngine2\

skip_tags: true

deploy:
  release: TDEngine2_SDK-v$(appveyor_build_version)-Win32
  description: ''
  provider: GitHub
  auth_token:
    secure: aKw3Gnd9exu0Fdz7DUdiOj36rMkyCc9h+5y2KlbLqBftXwm/Atq3wndgXnztWeKf
  artifact: /.*\.zip/            
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only