7z a TDEngine2_SDK.zip %APPVEYOR_BUILD_FOLDER%\TDEngine2\bin\%CONFIGURATION%\^
    %APPVEYOR_BUILD_FOLDER%\Resources^
    %APPVEYOR_BUILD_FOLDER%\README.md^
    %APPVEYOR_BUILD_FOLDER%\LICENSE^
    %APPVEYOR_BUILD_FOLDER%\CHANGELOG.md